In [1]:
"""
Esmé Middaugh 
2019JAN15

This notebook cleans the CDC mortality dataset collected by Kosali's team. Limits the years to 2006 to 2016 to match 
our prescription dataset. Once cleaned, merges the two datasets by year and state.
"""

"\nEsmé Middaugh \n2019JAN15\nThis notebook cleans the CDC mortality dataset collected by Kosali's team. Limits the years to 2006 to 2016 to match \nour prescription dataset. Once cleaned, merges the two datasets by year and state.\n"

In [2]:
import os
import pandas as pd

In [3]:
################ MORTALITY DATA #####################

fname = "../data/NCHS_-_Drug_Poisoning_Mortality_by_State__United_States.csv" # Assumes you are in 'code' and 'data' is another folder in parent directory
with open (fname) as f:
    mortality_df = pd.read_csv(f)

In [4]:
#Cleaning and aggregating the mortality data by State and Year 
"""
Original Mortality_df
mortality_df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2862 entries, 0 to 2861
"""
#Limiting to Our years:
mortality_df = mortality_df.query('Year >= 2006 and Year <=2016 and State != "United States"')

#After Limiting:
mortality_df.info()
"""
Data columns (total 19 columns):
State                                           1749 non-null object
Year                                            1749 non-null int64
Sex                                             1749 non-null object
Age Group                                       1749 non-null object
Race and Hispanic Origin                        1749 non-null object
Deaths                                          1749 non-null int64
Population                                      1749 non-null int64
Crude Death Rate                                1749 non-null float64
Standard Error for Crude Rate                   1749 non-null float64
Lower Confidence Limit for Crude Rate           1749 non-null float64
Upper Confidence Limit for Crude Rate           1749 non-null float64
Age-adjusted Rate                               693 non-null float64
Standard Error for Age-adjusted Rate            693 non-null float64
Lower Confidence Limit for Age-adjusted Rate    693 non-null float64
Upper Confidence Limit for Age-adjusted Rate    693 non-null float64
State Crude Rate in Range                       693 non-null object
US Crude Rate                                   1749 non-null float64
US Age-adjusted Rate                            1749 non-null float64
Unit                                            1749 non-null object
"""

<class 'pandas.core.frame.DataFrame'>
Int64Index: 561 entries, 7 to 2861
Data columns (total 19 columns):
State                                           561 non-null object
Year                                            561 non-null int64
Sex                                             561 non-null object
Age Group                                       561 non-null object
Race and Hispanic Origin                        561 non-null object
Deaths                                          561 non-null int64
Population                                      561 non-null int64
Crude Death Rate                                561 non-null float64
Standard Error for Crude Rate                   561 non-null float64
Lower Confidence Limit for Crude Rate           561 non-null float64
Upper Confidence Limit for Crude Rate           561 non-null float64
Age-adjusted Rate                               561 non-null float64
Standard Error for Age-adjusted Rate            561 non-null float64
Lower Confidence Limit for Age-adjusted Rate    561 non-null float64
Upper Confidence Limit for Age-adjusted Rate    561 non-null float64
State Crude Rate in Range                       561 non-null object
US Crude Rate                                   561 non-null float64
US Age-adjusted Rate                            561 non-null float64
Unit                                            561 non-null object
dtypes: float64(10), int64(3), object(6)
memory usage: 87.7+ KB

'\nData columns (total 19 columns):\nState                                           1749 non-null object\nYear                                            1749 non-null int64\nSex                                             1749 non-null object\nAge Group                                       1749 non-null object\nRace and Hispanic Origin                        1749 non-null object\nDeaths                                          1749 non-null int64\nPopulation                                      1749 non-null int64\nCrude Death Rate                                1749 non-null float64\nStandard Error for Crude Rate                   1749 non-null float64\nLower Confidence Limit for Crude Rate           1749 non-null float64\nUpper Confidence Limit for Crude Rate           1749 non-null float64\nAge-adjusted Rate                               693 non-null float64\nStandard Error for Age-adjusted Rate            693 non-null float64\nLower Confidence Limit for Age-adjusted Rate    693 non-null float64\nUpper Confidence Limit for Age-adjusted Rate    693 non-null float64\nState Crude Rate in Range                       693 non-null object\nUS Crude Rate                                   1749 non-null float64\nUS Age-adjusted Rate                            1749 non-null float64\nUnit                                            1749 non-null object\n'

In [5]:
####################PRESCRIPTION DATA#####################
#Importing the prescription DF
prescription_fname = "../data/merged_cdc_prescription_2006_2016.csv"
with open (prescription_fname) as f:
    prescription_df = pd.read_csv(f, index_col=0)
prescription_df.head()

        State State.ABBR  Prescribing.Rate  Year
0     Alabama         AL             115.6  2006
1      Alaska         AK              63.4  2006
2     Arizona         AZ              74.3  2006
3    Arkansas         AR              98.3  2006
4  California         CA              51.0  2006

In [6]:
#Merging the mortality and prescription DFs
full_df = pd.merge(mortality_df, prescription_df, on=['State', 'Year'])

#Checking out Alabama
full_df[full_df.State=='Alabama']

,State,Year,Sex,Age Group,Race and Hispanic Origin,Deaths,Population,Crude Death Rate,Standard Error for Crude Rate,Lower Confidence Limit for Crude Rate,...,Age-adjusted Rate,Standard Error for Age-adjusted Rate,Lower Confidence Limit for Age-adjusted Rate,Upper Confidence Limit for Age-adjusted Rate,State Crude Rate in Range,US Crude Rate,US Age-adjusted Rate,Unit,State.ABBR,Prescribing.Rate
0,Alabama,2006,Both Sexes,All Ages,All Races-All Origins,398,4628981,8.5980,0.43098,7.7533,...,8.7498,0.44162,7.8842,9.6154,7.1–10.2,11.5373,11.4883,"per 100,000 population",AL,115.6
1,Alabama,2007,Both Sexes,All Ages,All Races-All Origins,511,4672840,10.9355,0.48376,9.9874,...,11.0885,0.49516,10.1180,12.0590,10.3–12.6,11.9543,11.8775,"per 100,000 population",AL,120.3
2,Alabama,2008,Both Sexes,All Ages,All Races-All Origins,607,4718206,12.8651,0.52218,11.8416,...,12.9811,0.53292,11.9366,14.0256,12.6–16,11.9864,11.8947,"per 100,000 population",AL,126.1
3,Alabama,2009,Both Sexes,All Ages,All Races-All Origins,630,4757938,13.2410,0.52754,12.2071,...,13.6077,0.54855,12.5325,14.6828,12.6–16,12.0624,11.9388,"per 100,000 population",AL,131.6
4,Alabama,2010,Both Sexes,All Ages,All Races-All Origins,547,4779736,11.4441,0.48932,10.4851,...,11.7688,0.50959,10.7700,12.7676,10.3–12.6,12.4144,12.2966,"per 100,000 population",AL,134.3
5,Alabama,2011,Both Sexes,All Ages,All Races-All Origins,552,4802740,11.4934,0.48919,10.5346,...,11.7632,0.50803,10.7674,12.7589,10.3–12.6,13.2674,13.1852,"per 100,000 population",AL,136.6
6,Alabama,2012,Both Sexes,All Ages,All Races-All Origins,562,4822023,11.6549,0.49163,10.6913,...,12.0706,0.51722,11.0569,13.0844,10.3–12.6,13.2208,13.1422,"per 100,000 population",AL,143.8
7,Alabama,2013,Both Sexes,All Ages,All Races-All Origins,598,4833722,12.3714,0.50590,11.3798,...,12.7176,0.52933,11.6801,13.7551,12.6–16,13.9127,13.8005,"per 100,000 population",AL,142.4
8,Alabama,2014,Both Sexes,All Ages,All Races-All Origins,723,4849377,14.9091,0.55448,13.8224,...,15.1532,0.57484,14.0265,16.2799,12.6–16,14.7574,14.6831,"per 100,000 population",AL,135.2
9,Alabama,2015,Both Sexes,All Ages,All Races-All Origins,736,4858979,15.1472,0.55833,14.0529,...,15.6639,0.58859,14.5103,16.8176,12.6–16,16.3040,16.2923,"per 100,000 population",AL,125.0
10,Alabama,2016,Both Sexes,All Ages,All Races-All Origins,756,4863300,15.5450,0.56537,14.4369,...,16.2075,0.60241,15.0268,17.3883,16–52,19.6925,19.7851,"per 100,000 population",AL,121.0

In [7]:
full_df.info()
"""
<class 'pandas.core.frame.DataFrame'>
Int64Index: 561 entries, 0 to 560
Data columns (total 21 columns):
State                                           561 non-null object
Year                                            561 non-null int64
Sex                                             561 non-null object
Age Group                                       561 non-null object
Race and Hispanic Origin                        561 non-null object
Deaths                                          561 non-null int64
Population                                      561 non-null int64
Crude Death Rate                                561 non-null float64
Standard Error for Crude Rate                   561 non-null float64
Lower Confidence Limit for Crude Rate           561 non-null float64
Upper Confidence Limit for Crude Rate           561 non-null float64
Age-adjusted Rate                               561 non-null float64
Standard Error for Age-adjusted Rate            561 non-null float64
Lower Confidence Limit for Age-adjusted Rate    561 non-null float64
Upper Confidence Limit for Age-adjusted Rate    561 non-null float64
State Crude Rate in Range                       561 non-null object
US Crude Rate                                   561 non-null float64
US Age-adjusted Rate                            561 non-null float64
Unit                                            561 non-null object
State.ABBR                                      561 non-null object
Prescribing.Rate                                561 non-null float64
dtypes: float64(11), int64(3), object(7)
memory usage: 96.4+ KB
"""

<class 'pandas.core.frame.DataFrame'>
Int64Index: 561 entries, 0 to 560
Data columns (total 21 columns):
State                                           561 non-null object
Year                                            561 non-null int64
Sex                                             561 non-null object
Age Group                                       561 non-null object
Race and Hispanic Origin                        561 non-null object
Deaths                                          561 non-null int64
Population                                      561 non-null int64
Crude Death Rate                                561 non-null float64
Standard Error for Crude Rate                   561 non-null float64
Lower Confidence Limit for Crude Rate           561 non-null float64
Upper Confidence Limit for Crude Rate           561 non-null float64
Age-adjusted Rate                               561 non-null float64
Standard Error for Age-adjusted Rate            561 non-null float64
Lower Confidence Limit for Age-adjusted Rate    561 non-null float64
Upper Confidence Limit for Age-adjusted Rate    561 non-null float64
State Crude Rate in Range                       561 non-null object
US Crude Rate                                   561 non-null float64
US Age-adjusted Rate                            561 non-null float64
Unit                                            561 non-null object
State.ABBR                                      561 non-null object
Prescribing.Rate                                561 non-null float64
dtypes: float64(11), int64(3), object(7)
memory usage: 96.4+ KB

"\n<class 'pandas.core.frame.DataFrame'>\nInt64Index: 561 entries, 0 to 560\nData columns (total 21 columns):\nState                                           561 non-null object\nYear                                            561 non-null int64\nSex                                             561 non-null object\nAge Group                                       561 non-null object\nRace and Hispanic Origin                        561 non-null object\nDeaths                                          561 non-null int64\nPopulation                                      561 non-null int64\nCrude Death Rate                                561 non-null float64\nStandard Error for Crude Rate                   561 non-null float64\nLower Confidence Limit for Crude Rate           561 non-null float64\nUpper Confidence Limit for Crude Rate           561 non-null float64\nAge-adjusted Rate                               561 non-null float64\nStandard Error for Age-adjusted Rate            561 non-null float64\nLower Confidence Limit for Age-adjusted Rate    561 non-null float64\nUpper Confidence Limit for Age-adjusted Rate    561 non-null float64\nState Crude Rate in Range                       561 non-null object\nUS Crude Rate                                   561 non-null float64\nUS Age-adjusted Rate                            561 non-null float64\nUnit                                            561 non-null object\nState.ABBR                                      561 non-null object\nPrescribing.Rate                                561 non-null float64\ndtypes: float64(11), int64(3), object(7)\nmemory usage: 96.4+ KB\n"

In [8]:
#Writing this complete dataframe to a csv for use in Tableau 
full_df.to_csv('../data/cdc_prescription_mortality_2006_2016.csv')

In [9]:
#Checking the data to make sure it is working
indiana_df = full_df[full_df['State']=='Indiana']
full_df['State'].unique()
import numpy as np 
np.size(full_df['State'].unique())

51